const MessageConstant = {
  USER_NOT_FOUND: "User not found",
  USER_CREATED: "user created",
  USER_GET: "get all users",
  USER_GET_BY_ID: "get single users by id",
  USER_UPDATE: "user updated",
  USER_DELETE: "user deleted successfully",
  USER_ALREADY_EXIST: "User already exists",
  LOGIN_SUCCESS: "login successfully",
  INVALID_PASSWORD: "invalid password",
  USER_ACCOUNT_STATUS: "user accountd not active",

  FIRST_NAME_ONLY_ALPHABETS: "First name must contain only alphabets",
  MIDDLE_NAME_ONLY_ALPHABETS: "middleName must contain only alphabets",
  LAST_NAME_ONLY_ALPHABETS: "lastName must contain only alphabets",
  INVALID_EMAIL_FORMATE: "Invalid email formate",
  EMAIL_EXISTING: "Email already exists",
  PASSWORD_ERROR:
    "Password must contain uppercase, lowercase, number, special character and minimum 8 characters and required",
  AGE_NOT_NEGATIVE: "age cannot negative",
  INVALID_DATE: "Invalid date",
  DOB_MUST_AT_LEAT_YEAR_OLD: "You must be at least 18 years old",
  CITY_NAME_ONLY_ALPHABETS: "city must be in alphabet only!",
  STATE_ONLY_ALPHABETS: "state must be in alpahbates only!",
  ZIPCODE_ONLY_DIGITES: "zipcode must be in 5 or 6 digites",
  MOBILE_NUMBER_ONLY_10_DIGITES: "Enter Valid moblieNumber of 10 Digites",
  INVALID_GENDER: "Invalid gender value",
  INVALID_USERS_STATUS: "Invalid status value",
  INVALID_USERS_ROLE: "Invalid role value",
  VAIDATION_FAILD: "validation failed",
  SERVER_ERROR: " Internal server error",
  INVALID_EMAIL_PASSWORED: "invalid email or passwored",
  UNAUTHORIZED: "user is unauthorized",
  ACCESS_DENIED: "Access denied",
  ACCOUNT_BLOCK: "Account blocked",
  USER_UNBLOCKED: "User unblocked successfully",
  TOKEN_NOT_PROVIDED: "Token not provided",
  INVALID_TOKEN: "invalid token",
  OTP_SENT: "otp send in your email",
  OTP_NOT_FOUND: "opt not found",
  OTP_EXPIRED: "otp expired",
  INVALID_OTP: "invalid otp",
  INVALID_ACCEES_TYPE: "Invalid access type",
  ADMIN_LOGIN_SUCCESS: "admin login succcessfully",

  //ERROR MESSAGE
  ERROR: "ERROR",
  UNAUTHORIZED_ERROR: "Unauthorized access",
  BAD_REQUEST_ERROR: "Bad Request",
  SUCCESS: "SUCCESS",
  OK_RESPONSE: "OK",
  INVALID_REQUEST: "Invalid request",
  NOT_FOUND: "Not found",
  ALREADY_EXIST: "Already exists",
};
module.exports = MessageConstant;
